name: "BCRS CD action"
author: "Patrick Wei"
description: "CD for BCRS projects"
inputs:
  WORKING_DIRECTORY:
    description: "The application directory"
    required: true
  APP_NAME:
    description: "The application name"
    required: true
  SKIP_OP:
    description: "Skip running 1password script"
    required: true
    default: "false"
  DEPLOYMENT:
    description: "Deployment"
    required: false
    default: "true"
  OP_PARAMETERS:
    description: "The 1password script parameters"
    required: true
  OPENSHIFT_LOGIN_REGISTRY:
    description: "The openshift registry"
    required: true
  OPENSHIFT_DOCKER_REGISTRY:
    description: "The openshift docker registry"
    required: true
  OPENSHIFT_SA_NAME:
    description: "The openshift service account name"
    required: true
  OPENSHIFT_SA_TOKEN:
    description: "The openshift service account token"
    required: true
  OPENSHIFT_REPOSITORY:
    description: "The openshift repository"
    required: true
  OPENSHIFT_REPOSITORY_DEPLOYMENT:
    description: "The openshift repository from deployment"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install tools (1password)
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/install_tools.sh
        oc version
        op --version

    - name: Set Deployment Environement Variables
      shell: bash
      run: |
        oc login ${{inputs.OPENSHIFT_LOGIN_REGISTRY}} --token=${{inputs.OPENSHIFT_SA_TOKEN}}
        echo "Update Envs"
        ls -l
        vaults=`cat ./${{inputs.WORKING_DIRECTORY}}/devops/vaults.json`
        ${{ github.action_path }}/scripts/1pass.sh ${{inputs.OP_PARAMETERS}} -s "${{inputs.SKIP_OP}}" -m "secret" -e "${TAG_NAME}" -v "${vaults}" -a "${{inputs.APP_NAME}}-${TAG_NAME}" -n "${{inputs.OPENSHIFT_REPOSITORY}}-${TAG_NAME}" -r "${{inputs.DEPLOYMENT}}"

    - name: Build/Push image
      shell: bash
      run: |
        make cd

    - name: Watch new rollout (trigger by image change in Openshift)
      shell: bash
      run: |
        oc rollout status dc/${{inputs.APP_NAME}}-${TAG_NAME} -n ${{inputs.OPENSHIFT_REPOSITORY_DEPLOYMENT}}-${TAG_NAME} -w
